### ISSUE TITLE
Error between disclosureStart and disclosureEnd processing

### ISSUE THREAD

**Issue by hugoib** [adorsys/sd-jwt#15]
![Screenshot 2024-08-09 at 15 55 00](https://github.com/user-attachments/assets/6002404f-1d08-42ae-bfd4-6e050aae93f8)

There is an parsing error in this file: 

https://github.com/adorsys/sd-jwt/blob/d7fd670419df5e2634c69c2c1e2aa94ff7652fd0/src/main/java/de/adorsys/sdjwt/vp/SdJwtVP.java

Where if the length of disclosureStart == disclosureEnd then the value should be empty and only if End > Start the assignation should occur.

**Comment by IngridPuppet** [comment]
Do you mean the assignment on Line 88? Yes, I'm also seeing a problem with the call to `substring`.

**Comment by hugoib** [comment]
MR: https://github.com/adorsys/sd-jwt/pull/16

**Comment by Ogenbertrand** [comment]
I just merged this ticket, It is okay to contribute it to KeyCloak?

**Comment by nitch2019** [comment]
@francis-pouatcha pls check and confirmed

**Comment by nitch2019** [comment]
@Ogenbertrand create a PR and send it to KC
Pls check it with @IngridPuppet

**Comment by hugoib** [comment]
PR: 
- https://github.com/keycloak/keycloak/pull/33029

**Comment by nitch2019** [comment]
Waiting for final review from kc team
